---
title: "Index results 2024"
order: 0

format:
  html:
    page-layout: full
    toc: false
    anchor-sections: false
    css: results_index.css

sidebar: false
page-navigation: false

listing:
  id: "latest-listing"
  contents: /../content/posts
  type: grid
  categories: false
  sort:
    - "date desc"
    - "title desc"
  fields: [image, title, subtitle, author, date]
  date-format: "DD-MMM-YYYY"
  sort-ui: false
  filter-ui: false
  grid-item-border: false
  max-items: 6
  grid-columns: 3

execute: 
  echo: false
---

:::{.site-title-block .headline-results}
:::{.column-screen}
:::{.column-page-inset}
# Country A tops the 2024 edition of the Blavatnik Index of Public Administration {.headline-text}

:::{.grid}
:::{.g-col-12 .g-col-md-3 .fom-link}
[View the results](#executive-summary)
:::
:::{.g-col-12 .g-col-md-3 .fom-link}
[Read insights and interviews](/content/index.qmd)
:::
:::{.g-col-12 .g-col-md-3 .fom-link}
[Explore the data](/data_explorer/index.qmd)
:::
:::{.g-col-12 .g-col-md-3 .fom-link}
[Understand the methodology](/methodology/index.qmd)
:::
:::

:::
:::
:::

:::{.column-screen .headline-results}
:::{.column-page-inset}

:::{.headline-quote .align-left}
After an unprecedented year with elections in over 100 countries, the Blavatnik
Index of Public Administration provides crucial insights for officials and
ministers.

:::{.headline-author}
A N Other, Job title, Institution
:::
:::

:::{.headline-quote .align-right}
Through the Index civil service leaders can learn from peers in countries
they might not usually consider.

:::{.headline-author}
Y T Other, Job title, Institution
:::
:::


:::{.align-center}
[Read the foreward](foreword.qmd){.fom-link}
:::

:::
:::

:::{.column-screen .about-site}
:::{.column-page-inset}
## Executive summary

:::{.lead}
The 2024 Blavatnik Index of Public Administration covers 129 countries across
its 4 domains of strategy & leadership, public policy, national delivery, and
people & processes.
:::

Using its measurement framework, the Index brings together 168 individual data
points from 24 sources. Alongside the overall results of the Index, through this
website you can: read articles discussing themes and countries covered in the
results and interviews with those leading reform efforts, explore the data
in-depth, and read the technical methodology.

:::{.align-center}
[Read the executive summary](exec_summary.qmd){.fom-link}
:::
:::
:::

:::{.column-page-inset}
:::{.latest-content}
## 2024 results

:::{.lead}
Country A tops the 2024 Index.
:::

```{ojs, results_chart}

Plot = import("https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6.14/+esm");

dummy_data = [
  {cc_iso3c: "CC001", value: 1.000, hover_label:   "Country 1: 1.000", country_group: "Global Index"},
  {cc_iso3c: "CC002", value: 0.990, hover_label:   "Country 2: 0.990", country_group: "Global Index"},
  {cc_iso3c: "CC003", value: 0.980, hover_label:   "Country 3: 0.980", country_group: "Global Index"},
  {cc_iso3c: "CC004", value: 0.970, hover_label:   "Country 4: 0.970", country_group: "Global Index"},
  {cc_iso3c: "CC005", value: 0.960, hover_label:   "Country 5: 0.960", country_group: "Global Index"},
  {cc_iso3c: "CC006", value: 0.949, hover_label:   "Country 6: 0.949", country_group: "Global Index"},
  {cc_iso3c: "CC007", value: 0.939, hover_label:   "Country 7: 0.939", country_group: "Global Index"},
  {cc_iso3c: "CC008", value: 0.929, hover_label:   "Country 8: 0.929", country_group: "Global Index"},
  {cc_iso3c: "CC009", value: 0.919, hover_label:   "Country 9: 0.919", country_group: "Global Index"},
  {cc_iso3c: "CC010", value: 0.909, hover_label:  "Country 10: 0.909", country_group: "Global Index"},
  {cc_iso3c: "CC011", value: 0.899, hover_label:  "Country 11: 0.899", country_group: "Global Index"},
  {cc_iso3c: "CC012", value: 0.889, hover_label:  "Country 12: 0.889", country_group: "Global Index"},
  {cc_iso3c: "CC013", value: 0.879, hover_label:  "Country 13: 0.879", country_group: "Global Index"},
  {cc_iso3c: "CC014", value: 0.869, hover_label:  "Country 14: 0.869", country_group: "Global Index"},
  {cc_iso3c: "CC015", value: 0.859, hover_label:  "Country 15: 0.859", country_group: "Global Index"},
  {cc_iso3c: "CC016", value: 0.848, hover_label:  "Country 16: 0.848", country_group: "Global Index"},
  {cc_iso3c: "CC017", value: 0.838, hover_label:  "Country 17: 0.838", country_group: "Global Index"},
  {cc_iso3c: "CC018", value: 0.828, hover_label:  "Country 18: 0.828", country_group: "Global Index"},
  {cc_iso3c: "CC019", value: 0.818, hover_label:  "Country 19: 0.818", country_group: "Global Index"},
  {cc_iso3c: "CC020", value: 0.808, hover_label:  "Country 20: 0.808", country_group: "Global Index"},
  {cc_iso3c: "CC021", value: 0.798, hover_label:  "Country 21: 0.798", country_group: "Global Index"},
  {cc_iso3c: "CC022", value: 0.788, hover_label:  "Country 22: 0.788", country_group: "Global Index"},
  {cc_iso3c: "CC023", value: 0.778, hover_label:  "Country 23: 0.778", country_group: "Global Index"},
  {cc_iso3c: "CC024", value: 0.768, hover_label:  "Country 24: 0.768", country_group: "Global Index"},
  {cc_iso3c: "CC025", value: 0.758, hover_label:  "Country 25: 0.758", country_group: "Global Index"},
  {cc_iso3c: "CC026", value: 0.747, hover_label:  "Country 26: 0.747", country_group: "Global Index"},
  {cc_iso3c: "CC027", value: 0.737, hover_label:  "Country 27: 0.737", country_group: "Global Index"},
  {cc_iso3c: "CC028", value: 0.727, hover_label:  "Country 28: 0.727", country_group: "Global Index"},
  {cc_iso3c: "CC029", value: 0.717, hover_label:  "Country 29: 0.717", country_group: "Global Index"},
  {cc_iso3c: "CC030", value: 0.707, hover_label:  "Country 30: 0.707", country_group: "Global Index"},
  {cc_iso3c: "CC031", value: 0.697, hover_label:  "Country 31: 0.697", country_group: "Global Index"},
  {cc_iso3c: "CC032", value: 0.687, hover_label:  "Country 32: 0.687", country_group: "Global Index"},
  {cc_iso3c: "CC033", value: 0.677, hover_label:  "Country 33: 0.677", country_group: "Global Index"},
  {cc_iso3c: "CC034", value: 0.667, hover_label:  "Country 34: 0.667", country_group: "Global Index"},
  {cc_iso3c: "CC035", value: 0.657, hover_label:  "Country 35: 0.657", country_group: "Global Index"},
  {cc_iso3c: "CC036", value: 0.646, hover_label:  "Country 36: 0.646", country_group: "Global Index"},
  {cc_iso3c: "CC037", value: 0.636, hover_label:  "Country 37: 0.636", country_group: "Global Index"},
  {cc_iso3c: "CC038", value: 0.626, hover_label:  "Country 38: 0.626", country_group: "Global Index"},
  {cc_iso3c: "CC039", value: 0.616, hover_label:  "Country 39: 0.616", country_group: "Global Index"},
  {cc_iso3c: "CC040", value: 0.606, hover_label:  "Country 40: 0.606", country_group: "Global Index"},
  {cc_iso3c: "CC041", value: 0.596, hover_label:  "Country 41: 0.596", country_group: "Global Index"},
  {cc_iso3c: "CC042", value: 0.586, hover_label:  "Country 42: 0.586", country_group: "Global Index"},
  {cc_iso3c: "CC043", value: 0.576, hover_label:  "Country 43: 0.576", country_group: "Global Index"},
  {cc_iso3c: "CC044", value: 0.566, hover_label:  "Country 44: 0.566", country_group: "Global Index"},
  {cc_iso3c: "CC045", value: 0.556, hover_label:  "Country 45: 0.556", country_group: "Global Index"},
  {cc_iso3c: "CC046", value: 0.545, hover_label:  "Country 46: 0.545", country_group: "Global Index"},
  {cc_iso3c: "CC047", value: 0.535, hover_label:  "Country 47: 0.535", country_group: "Global Index"},
  {cc_iso3c: "CC048", value: 0.525, hover_label:  "Country 48: 0.525", country_group: "Global Index"},
  {cc_iso3c: "CC049", value: 0.515, hover_label:  "Country 49: 0.515", country_group: "Global Index"},
  {cc_iso3c: "CC050", value: 0.505, hover_label:  "Country 50: 0.505", country_group: "Global Index"},
  {cc_iso3c: "CC051", value: 0.495, hover_label:  "Country 51: 0.495", country_group: "Global Index"},
  {cc_iso3c: "CC052", value: 0.485, hover_label:  "Country 52: 0.485", country_group: "Global Index"},
  {cc_iso3c: "CC053", value: 0.475, hover_label:  "Country 53: 0.475", country_group: "Global Index"},
  {cc_iso3c: "CC054", value: 0.465, hover_label:  "Country 54: 0.465", country_group: "Global Index"},
  {cc_iso3c: "CC055", value: 0.455, hover_label:  "Country 55: 0.455", country_group: "Global Index"},
  {cc_iso3c: "CC056", value: 0.444, hover_label:  "Country 56: 0.444", country_group: "Global Index"},
  {cc_iso3c: "CC057", value: 0.434, hover_label:  "Country 57: 0.434", country_group: "Global Index"},
  {cc_iso3c: "CC058", value: 0.424, hover_label:  "Country 58: 0.424", country_group: "Global Index"},
  {cc_iso3c: "CC059", value: 0.414, hover_label:  "Country 59: 0.414", country_group: "Global Index"},
  {cc_iso3c: "CC060", value: 0.404, hover_label:  "Country 60: 0.404", country_group: "Global Index"},
  {cc_iso3c: "CC061", value: 0.394, hover_label:  "Country 61: 0.394", country_group: "Global Index"},
  {cc_iso3c: "CC062", value: 0.384, hover_label:  "Country 62: 0.384", country_group: "Global Index"},
  {cc_iso3c: "CC063", value: 0.374, hover_label:  "Country 63: 0.374", country_group: "Global Index"},
  {cc_iso3c: "CC064", value: 0.364, hover_label:  "Country 64: 0.364", country_group: "Global Index"},
  {cc_iso3c: "CC065", value: 0.354, hover_label:  "Country 65: 0.354", country_group: "Global Index"},
  {cc_iso3c: "CC066", value: 0.343, hover_label:  "Country 66: 0.343", country_group: "Global Index"},
  {cc_iso3c: "CC067", value: 0.333, hover_label:  "Country 67: 0.333", country_group: "Global Index"},
  {cc_iso3c: "CC068", value: 0.323, hover_label:  "Country 68: 0.323", country_group: "Global Index"},
  {cc_iso3c: "CC069", value: 0.313, hover_label:  "Country 69: 0.313", country_group: "Global Index"},
  {cc_iso3c: "CC070", value: 0.303, hover_label:  "Country 70: 0.303", country_group: "Global Index"},
  {cc_iso3c: "CC071", value: 0.293, hover_label:  "Country 71: 0.293", country_group: "Global Index"},
  {cc_iso3c: "CC072", value: 0.283, hover_label:  "Country 72: 0.283", country_group: "Global Index"},
  {cc_iso3c: "CC073", value: 0.273, hover_label:  "Country 73: 0.273", country_group: "Global Index"},
  {cc_iso3c: "CC074", value: 0.263, hover_label:  "Country 74: 0.263", country_group: "Global Index"},
  {cc_iso3c: "CC075", value: 0.253, hover_label:  "Country 75: 0.253", country_group: "Global Index"},
  {cc_iso3c: "CC076", value: 0.242, hover_label:  "Country 76: 0.242", country_group: "Global Index"},
  {cc_iso3c: "CC077", value: 0.232, hover_label:  "Country 77: 0.232", country_group: "Global Index"},
  {cc_iso3c: "CC078", value: 0.222, hover_label:  "Country 78: 0.222", country_group: "Global Index"},
  {cc_iso3c: "CC079", value: 0.212, hover_label:  "Country 79: 0.212", country_group: "Global Index"},
  {cc_iso3c: "CC080", value: 0.202, hover_label:  "Country 80: 0.202", country_group: "Global Index"},
  {cc_iso3c: "CC081", value: 0.192, hover_label:  "Country 81: 0.192", country_group: "Global Index"},
  {cc_iso3c: "CC082", value: 0.182, hover_label:  "Country 82: 0.182", country_group: "Global Index"},
  {cc_iso3c: "CC083", value: 0.172, hover_label:  "Country 83: 0.172", country_group: "Global Index"},
  {cc_iso3c: "CC084", value: 0.162, hover_label:  "Country 84: 0.162", country_group: "Global Index"},
  {cc_iso3c: "CC085", value: 0.152, hover_label:  "Country 85: 0.152", country_group: "Global Index"},
  {cc_iso3c: "CC086", value: 0.141, hover_label:  "Country 86: 0.141", country_group: "Global Index"},
  {cc_iso3c: "CC087", value: 0.131, hover_label:  "Country 87: 0.131", country_group: "Global Index"},
  {cc_iso3c: "CC088", value: 0.121, hover_label:  "Country 88: 0.121", country_group: "Global Index"},
  {cc_iso3c: "CC089", value: 0.111, hover_label:  "Country 89: 0.111", country_group: "Global Index"},
  {cc_iso3c: "CC090", value: 0.101, hover_label:  "Country 90: 0.101", country_group: "Global Index"},
  {cc_iso3c: "CC091", value: 0.091, hover_label:  "Country 91: 0.091", country_group: "Global Index"},
  {cc_iso3c: "CC092", value: 0.081, hover_label:  "Country 92: 0.081", country_group: "Global Index"},
  {cc_iso3c: "CC093", value: 0.071, hover_label:  "Country 93: 0.071", country_group: "Global Index"},
  {cc_iso3c: "CC094", value: 0.061, hover_label:  "Country 94: 0.061", country_group: "Global Index"},
  {cc_iso3c: "CC095", value: 0.051, hover_label:  "Country 95: 0.051", country_group: "Global Index"},
  {cc_iso3c: "CC096", value: 0.040, hover_label:  "Country 96: 0.040", country_group: "Global Index"},
  {cc_iso3c: "CC097", value: 0.030, hover_label:  "Country 97: 0.030", country_group: "Global Index"},
  {cc_iso3c: "CC098", value: 0.020, hover_label:  "Country 98: 0.020", country_group: "Global Index"},
  {cc_iso3c: "CC099", value: 0.010, hover_label:  "Country 99: 0.010", country_group: "Global Index"},
  {cc_iso3c: "CC100", value: 0.000, hover_label: "Country 100: 0.000", country_group: "Global Index"}
]

Plot.plot({
  width: 1000,
  height: 400,
  marginLeft: 0,
  marginRight: 0,
  x: {label: null, axis: null},
  y: {label: null, grid: null, domain: [-0.1, 1], ticks: 0},
  marks: [
    Plot.barY(dummy_data, {
      x: "cc_iso3c",
      y: "value",
      fill: "#00629B",
      sort: {x: "y", reverse: true}
    }),
    Plot.text(dummy_data, {
      x: "cc_iso3c",
      y: -0.01,
      text: "cc_iso3c",
      fill: "#00629B",
      textAnchor: "end",
      rotate: 270,
      sort: {x: "y", reverse: true}
    }),
    Plot.tip(dummy_data,
      Plot.pointerX({
        x: "cc_iso3c",
        y: "value",
        filter: (d) => d.hover_label,
        title: (d) => d.hover_label,
        frameAnchor: "left"
      })
    )
  ]
})
```

:::{.align-center}
[Read more about the overall Index results](overall_results.qmd){.fom-link}
:::

:::{.grid}
:::{.g-col-12 .g-col-md-6}
### Strategy & leadership
Country B ranks highest for strategy & leadership with particular strengths in
strategic capacity and openness & communictions, while Country D comes highest
in trust & integrity.

[Read more](domain1_results.qmd){.fom-link}
:::
:::{.g-col-12 .g-col-md-6}
### Public policy
Country A ranks highest for public policy, while Country C comes
in top for regulation.

[Read more](domain1_results.qmd){.fom-link}
:::
:::
:::{.grid}
:::{.g-col-12 .g-col-md-6}
### National delivery
Country A ranks highest for national delivery with the highest scores for both
system oversight and digital services.

[Read more](domain1_results.qmd){.fom-link}
:::
:::{.g-col-12 .g-col-md-6}
### People & processes
Country B ranks highest for domain 4 with the highest scores
for diversity & inclusion, country C ranks highest for HR management and
country D comes top in procurement.

[Read more](domain1_results.qmd){.fom-link}
:::
:::{.g-col-12 .g-col-md-6}
### Results by regional and economic groupings
The benefit of our global approach allows for rich insights by regional and
economic groupings. Country X comes top in Sub-Saharan Africa, while County Y
is the highest scoring low income country.

[Read more](domain1_results.qmd){.fom-link}
:::
:::{.g-col-12 .g-col-md-6}
### Conclusions & next steps
The results provide an important tool to help countries learn from each other,
however there remain crucial gaps in the availability of data to fully
understand how public administrations compare.

[Read more](domain1_results.qmd){.fom-link}
:::
:::




:::{.make-use}
### Making use of the results

:::{.grid}
:::{.g-col-12 .g-col-md-8}
There are many different ways you can make use of the results from the 2024
Index, read the results content, explore the data, or read articles and
interviews that provide reflections on the results.

For more ideas and details on how you can make full use of the results, read
our [in-depth guide](/data_explorer/user_guide.qmd).
:::

:::{.g-col-12 .g-col-md-4 .draft-image}
image
:::
:::

:::

:::
:::


:::{.column-screen .about-site}
:::{.column-page-inset}
## Explore the data

:::{.grid}
:::{.g-col-12 .g-col-md-4 .draft-image}
image
:::

:::{.g-col-12 .g-col-md-8}
Through our data explorer tool you can interrogate the results for your
country in-depth, review individual metrics or download the datasets for
your own further analysis.

[Explore the data](/data_explorer/index.qmd){.fom-link}

The Index brings together X individual data points from Y sources, grouped
around our framework, our methodology articles provide details on the approach
we take to data processing and analysis.

[Understand the methodology](/methodology/index.qmd){.fom-link}

:::

:::
:::
:::

:::{.column-page-inset}
:::{.latest-content}
## Latest insights

:::{.article-listing}
:::{#latest-listing}
:::
:::

[More opinion, insight and research](/content/index.qmd){.fom-link}

:::
:::

