project:
  type: website

website:
  title: "International Civil Service Effectiveness Index"
  navbar:
    logo: imgs/bsg-logo.svg
    logo-alt: "Blavatnik School of Government logo"
    title: "The International Civil Service Effectiveness Index"
    right:
      - text: "2024 Results"
        href: "about/index.qmd"
      - text: "Blog"
        href: "content/index.qmd"
      - text: "Data"
        href: "about/index.qmd"
      - text: "More"
        menu:
          - text: "About"
            href: "about/index.qmd"
          - text: "Methodology"
            href: "about/index.qmd"
          - text: "The Blavatnik School of Government"
            href: "https://www.bsg.ox.ac.uk"


format:
  html:
    theme: [bsg.scss]
    css: bsg.css
    toc: true
    include-in-header: _banner.html
    date-format: "DD MMM YYYY"
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 200px

execute:
  freeze: true
